Dockerfile.txt
Created Thu Dec 28 10:12:26 AKST 2017
Copyright (C) 2017 by Raymond E. Marcil <marcilr@gmail.com>


Dockerfile


Define your app’s environment with a Dockerfile so it can
be reproduced anywhere.
--docs.docker.com/compose/overview/


Links
=====
Overview of Docker Compose
https://docs.docker.com/compose/overview/

