Dockerfile.txt
Created Sun Mar 18 14:02:00 AKDT 2018
Copyright (C) 2018 by Raymond E. Marcil <marcilr@gmail.com>


The Dockerfile defines "exactly what needs to be included in the container."[1]


FROM ruby:2.3.3
RUN apt-get update -qq && apt-get install -y build-essential libpq-dev nodejs
RUN mkdir /myapp
WORKDIR /myapp
COPY Gemfile /myapp/Gemfile
COPY Gemfile.lock /myapp/Gemfile.lock
RUN bundle install
COPY . /myapp


Links
=====
[1] Quickstart: Compose and Rails
https://docs.docker.com/compose/rails/

Docker user guide
"Hot to write Dockerfiles"[1]
https://docs.docker.com/engine/tutorials/dockerimages/#building-an-image-from-a-dockerfile

Docker reference
"Hot to write Dockerfiles"[1]
https://docs.docker.com/engine/reference/builder/
